#!/usr/bin/env bash
#
# Builds TDLib for iOS into ios/Frameworks/tdjson.xcframework.
#
# handy_tdlib ships TDLib for Android only. This builds the same TDLib commit
# from source, with OpenSSL, for iPhones and for the simulator on Apple
# silicon. It needs Xcode, CMake and gperf, and takes a while. Run it again
# after changing TD_COMMIT or OPENSSL_VERSION.
set -euo pipefail

# The commit handy_tdlib's Dart API was generated from (TDLib 1.8.36). Keep
# the two in step: a different TDLib can send objects the Dart side cannot
# parse, or reject requests it builds.
TD_COMMIT=87d881071fe514936bb17029e96761141287d2be
TD_VERSION=1.8.36

OPENSSL_VERSION=3.5.9
OPENSSL_SHA256=603f5602e2eef00d77fbd429d34dcd5822bb301757a1bc9cdb24c670f1eb859a

# Matches IPHONEOS_DEPLOYMENT_TARGET in ios/Runner.xcodeproj.
MIN_IOS=15.0

root="$(cd "$(dirname "$0")/.." && pwd)"
work="$root/build/tdlib-ios"
out="$root/ios/Frameworks/tdjson.xcframework"
jobs="$(sysctl -n hw.ncpu)"

for tool in cmake gperf xcodebuild; do
  command -v "$tool" > /dev/null || { echo "$tool is required" >&2; exit 1; }
done

mkdir -p "$work"
cd "$work"

# Sources.
if [ ! -d td ]; then
  git clone https://github.com/tdlib/td.git td
fi
git -C td cat-file -e "$TD_COMMIT^{commit}" 2> /dev/null || git -C td fetch origin
git -C td checkout -q "$TD_COMMIT"

openssl_tar="openssl-$OPENSSL_VERSION.tar.gz"
if [ ! -f "$openssl_tar" ]; then
  curl -fL -o "$openssl_tar.part" \
    "https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL_VERSION/$openssl_tar"
  mv "$openssl_tar.part" "$openssl_tar"
fi
echo "$OPENSSL_SHA256  $openssl_tar" | shasum -a 256 -c -

# Part of TDLib's source is generated by tools built for this Mac.
cmake -S td -B native -DCMAKE_BUILD_TYPE=Release \
  -DTD_GENERATE_SOURCE_FILES=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5
cmake --build native --target prepare_cross_compiling -j "$jobs"

# $1: SDK name, $2: OpenSSL target, $3: minimum version flag.
build_openssl() {
  local prefix="$work/openssl-$1"
  [ -f "$prefix/lib/libcrypto.a" ] && return
  local src="$work/openssl-src-$1"
  rm -rf "$src"
  mkdir -p "$src"
  tar xzf "$openssl_tar" -C "$src" --strip-components 1
  (
    cd "$src"
    ./Configure "$2" no-shared no-tests no-apps no-docs no-engine no-async \
      "$3=$MIN_IOS" --prefix="$prefix" --libdir=lib
    make -j "$jobs" build_libs
    make install_dev
  )
}

# $1: SDK name.
build_td() {
  local ssl="$work/openssl-$1"
  cmake -S td -B "td-$1" \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_SYSROOT="$1" \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DCMAKE_OSX_DEPLOYMENT_TARGET="$MIN_IOS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DOPENSSL_FOUND=1 \
    -DOPENSSL_INCLUDE_DIR="$ssl/include" \
    -DOPENSSL_CRYPTO_LIBRARY="$ssl/lib/libcrypto.a" \
    -DOPENSSL_SSL_LIBRARY="$ssl/lib/libssl.a" \
    -DOPENSSL_LIBRARIES="$ssl/lib/libssl.a;$ssl/lib/libcrypto.a"
  cmake --build "td-$1" --target tdjson -j "$jobs"
}

# The App Store takes dynamic libraries only inside frameworks.
# $1: SDK name, $2: platform name for Info.plist.
make_framework() {
  local framework="$work/frameworks/$1/tdjson.framework"
  rm -rf "$framework"
  mkdir -p "$framework"
  cp -L "td-$1/libtdjson.dylib" "$framework/tdjson"
  install_name_tool -id @rpath/tdjson.framework/tdjson "$framework/tdjson"
  strip -x "$framework/tdjson"
  cat > "$framework/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>tdjson</string>
	<key>CFBundleIdentifier</key>
	<string>dev.ragoose.gramx.tdjson</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>tdjson</string>
	<key>CFBundlePackageType</key>
	<string>FMWK</string>
	<key>CFBundleShortVersionString</key>
	<string>$TD_VERSION</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>$2</string>
	</array>
	<key>MinimumOSVersion</key>
	<string>$MIN_IOS</string>
</dict>
</plist>
PLIST
}

build_openssl iphoneos ios64-xcrun -mios-version-min
build_openssl iphonesimulator iossimulator-arm64-xcrun -mios-simulator-version-min
build_td iphoneos
build_td iphonesimulator
make_framework iphoneos iPhoneOS
make_framework iphonesimulator iPhoneSimulator

rm -rf "$out"
xcodebuild -create-xcframework \
  -framework "$work/frameworks/iphoneos/tdjson.framework" \
  -framework "$work/frameworks/iphonesimulator/tdjson.framework" \
  -output "$out"
echo "Built $out"
