// Writes the website's privacy policy and terms (docs/privacy.html and
// docs/terms.html) from lib/core/l10n/legal_text.dart, so the site and the
// app always say the same thing. Run it after changing either document:
//
//   dart run tool/site_legal.dart
import 'dart:io';

import 'package:gramx/core/l10n/legal_text.dart';

/// Where the site is published. Keep in step with docs/index.html.
const _siteUrl = 'https://daveragos.github.io/gramx/';

void main() {
  _write('privacy', LegalTexts.privacy);
  _write('terms', LegalTexts.terms);
}

void _write(String slug, LegalDocument doc) {
  final file = File('docs/$slug.html');
  file.writeAsStringSync(_page(slug, doc));
  stdout.writeln('Wrote ${file.path}');
}

String _escape(String text) => text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');

/// Escapes [text] and links the contact address.
String _paragraph(String text) {
  const email = LegalTexts.contactEmail;
  return _escape(text).replaceAll(email, '<a href="mailto:$email">$email</a>');
}

String _icon(String id) =>
    '<svg class="i" aria-hidden="true"><use href="assets/icons.svg#i-$id"/></svg>';

String _page(String slug, LegalDocument doc) {
  final body = StringBuffer();
  for (final section in doc.sections) {
    body.writeln('    <h2>${_escape(section.heading)}</h2>');
    for (final p in section.paragraphs) {
      body.writeln('    <p>${_paragraph(p)}</p>');
    }
  }

  return '''<!doctype html>
<!-- Generated by tool/site_legal.dart from lib/core/l10n/legal_text.dart. Do not edit. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>${_escape(doc.title)} · gramX</title>
  <meta name="description" content="${_escape(doc.summary)}">
  <link rel="canonical" href="$_siteUrl$slug.html">
  <meta name="theme-color" content="#000000">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32.png">
  <link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
  <link rel="preload" href="assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="styles.css">
  <script>
    (function () {
      var d = document.documentElement, t = null;
      try { t = localStorage.getItem('gramx-theme'); } catch (e) {}
      if (t !== 'light' && t !== 'dim' && t !== 'dark') {
        t = window.matchMedia && matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
      }
      d.setAttribute('data-theme', t);
    })();
  </script>
  <script src="site.js" defer></script>
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>

  <header class="nav" data-nav>
    <div class="container nav-inner">
      <a class="brand" href="./" aria-label="gramX home">
        <img class="on-dark" src="assets/brand/glyph-on-dark.png" alt="" width="24" height="26">
        <img class="on-light" src="assets/brand/glyph-on-light.png" alt="" width="24" height="26">
        <span>gramX</span>
      </a>
      <div class="nav-actions">
        <button class="icon-btn theme-toggle" type="button" data-theme-cycle aria-label="Change theme">
          <svg class="i t-light" aria-hidden="true"><use href="assets/icons.svg#i-sun"/></svg>
          <svg class="i t-dim" aria-hidden="true"><use href="assets/icons.svg#i-dim"/></svg>
          <svg class="i t-dark" aria-hidden="true"><use href="assets/icons.svg#i-moon"/></svg>
        </button>
        <a class="btn btn-primary btn-sm" href="./#install">Download</a>
      </div>
    </div>
  </header>

  <main id="main" class="container doc">
    <a class="back" href="./">${_icon('arrow')}gramX home</a>
    <h1>${_escape(doc.title)}</h1>
    <p class="updated">Last updated ${_escape(doc.lastUpdated)}</p>
    <p class="summary">${_paragraph(doc.summary)}</p>
$body  </main>

  <footer class="footer">
    <div class="container">
      <div class="footer-top">
        <a class="brand" href="./" aria-label="gramX home">
          <img class="on-dark" src="assets/brand/glyph-on-dark.png" alt="" width="24" height="26">
          <img class="on-light" src="assets/brand/glyph-on-light.png" alt="" width="24" height="26">
          <span>gramX</span>
        </a>
        <nav class="footer-links" aria-label="Footer">
          <a href="./#install">Download</a>
          <a href="privacy.html">Privacy Policy</a>
          <a href="terms.html">Terms of Service</a>
          <a href="https://github.com/daveragos/gramx">Source code</a>
          <a href="https://github.com/daveragos/gramx/issues">Report an issue</a>
        </nav>
      </div>
      <p class="fine">gramX is an independent app. It is not made by, affiliated with, or endorsed by Telegram.</p>
    </div>
  </footer>
</body>
</html>
''';
}
